/**
 * Song-Katalog mit allen vorinstallierten Liedern.
 * Dient sowohl als statische Absicherung (z. B. bei Öffnen über file:// ohne Server)
 * als auch als Verzeichnis für dynamisches Nachladen.
 */

export const BUILTIN_SONGS = [
  {
    id: "smoke",
    title: "Smoke on the Water",
    artist: "Deep Purple",
    category: "Rock",
    bpm: 112,
    timeSignature: [4, 4],
    description: "Riff auf D- und G-Saite (Bund 0-3)",
    notes: [
      { midi: 50, duration: 1 },
      { midi: 53, duration: 1 },
      { midi: 55, duration: 2 },
      { midi: 50, duration: 1 },
      { midi: 53, duration: 1 },
      { midi: 56, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 50, duration: 1 },
      { midi: 53, duration: 1 },
      { midi: 55, duration: 2 },
      { midi: 53, duration: 1 },
      { midi: 50, duration: 1 },
      { midi: 50, duration: 2 }
    ]
  },
  {
    id: "seven_nation",
    title: "Seven Nation Army",
    artist: "The White Stripes",
    category: "Rock",
    bpm: 120,
    timeSignature: [4, 4],
    description: "Kult-Basslinie auf der Gitarre (E- und A-Saite)",
    notes: [
      { midi: 40, duration: 2 },
      { midi: 40, duration: 1 },
      { midi: 43, duration: 1 },
      { midi: 40, duration: 1 },
      { midi: 38, duration: 1 },
      { midi: 36, duration: 2 },
      { midi: 47, duration: 4 },
      { midi: 40, duration: 2 },
      { midi: 40, duration: 1 },
      { midi: 43, duration: 1 },
      { midi: 40, duration: 1 },
      { midi: 38, duration: 1 },
      { midi: 36, duration: 1 },
      { midi: 38, duration: 1 },
      { midi: 36, duration: 2 },
      { midi: 47, duration: 2 }
    ]
  },
  {
    id: "nem_intro",
    title: "Nothing Else Matters (Intro)",
    artist: "Metallica",
    category: "Rock",
    bpm: 92,
    timeSignature: [4, 4],
    description: "Berühmtes Fingerpicking-Intro auf leeren Saiten",
    notes: [
      { midi: 40, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 59, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 59, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 40, duration: 2 },
      { midi: 40, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 59, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 59, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 40, duration: 1 }
    ]
  },
  {
    id: "ode",
    title: "Ode an die Freude",
    artist: "Ludwig van Beethoven",
    category: "Klassik",
    bpm: 108,
    timeSignature: [4, 4],
    description: "Europahymne in C-Dur auf den hohen Saiten",
    notes: [
      { midi: 64, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 64, duration: 2 },
      { midi: 62, duration: 2 },
      { midi: 64, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 62, duration: 2 },
      { midi: 60, duration: 2 }
    ]
  },
  {
    id: "frere",
    title: "Frère Jacques",
    artist: "Traditional",
    category: "Traditionals",
    bpm: 100,
    timeSignature: [4, 4],
    description: "Klassischer Kanon (C-Dur)",
    notes: [
      { midi: 60, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 67, duration: 2 },
      { midi: 64, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 67, duration: 2 },
      { midi: 67, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 60, duration: 2 },
      { midi: 60, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 60, duration: 2 }
    ]
  },
  {
    id: "haenschen",
    title: "Hänschen klein",
    artist: "Traditional",
    category: "Traditionals",
    bpm: 104,
    timeSignature: [4, 4],
    description: "Traditionelles Volkslied (C-Dur)",
    notes: [
      { midi: 67, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 64, duration: 2 },
      { midi: 65, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 62, duration: 2 },
      { midi: 60, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 67, duration: 2 },
      { midi: 67, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 64, duration: 2 },
      { midi: 65, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 62, duration: 2 },
      { midi: 60, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 60, duration: 4 }
    ]
  },
  {
    id: "old_mcdonald",
    title: "Old McDonald",
    artist: "Traditionell",
    category: "Traditionals",
    bpm: 100,
    timeSignature: [4, 4],
    description: "Klassisches Kinder- und Volkslied",
    notes: [
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 57, duration: 1, string: 2, fret: 2 },
      { midi: 59, duration: 1, string: 1, fret: 0 },
      { midi: 59, duration: 1, string: 1, fret: 0 },
      { midi: 57, duration: 2, string: 2, fret: 2 },
      { midi: 66, duration: 1, string: 0, fret: 2 },
      { midi: 66, duration: 1, string: 0, fret: 2 },
      { midi: 64, duration: 1, string: 0, fret: 0 },
      { midi: 64, duration: 1, string: 0, fret: 0 },
      { midi: 62, duration: 4, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 57, duration: 1, string: 2, fret: 2 },
      { midi: 59, duration: 1, string: 1, fret: 0 },
      { midi: 59, duration: 1, string: 1, fret: 0 },
      { midi: 57, duration: 2, string: 2, fret: 2 },
      { midi: 66, duration: 1, string: 0, fret: 2 },
      { midi: 66, duration: 1, string: 0, fret: 2 },
      { midi: 64, duration: 1, string: 0, fret: 0 },
      { midi: 64, duration: 1, string: 0, fret: 0 },
      { midi: 62, duration: 4, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 57, duration: 1, string: 2, fret: 2 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 57, duration: 1, string: 2, fret: 2 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 57, duration: 1, string: 2, fret: 2 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 57, duration: 1, string: 2, fret: 2 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 62, duration: 1, string: 1, fret: 3 },
      { midi: 59, duration: 1, string: 1, fret: 0 },
      { midi: 57, duration: 1, string: 2, fret: 2 }
    ]
  },
  {
    id: "sweet_child",
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    category: "Rock",
    bpm: 125,
    timeSignature: [4, 4],
    description: "Das legendäre Intro-Lick von Slash (Bund 12 bis 15)",
    notes: [
      { midi: 62, duration: 0.5, string: 3, fret: 12 },
      { midi: 74, duration: 0.5, string: 1, fret: 15 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },
      { midi: 67, duration: 0.5, string: 2, fret: 12 },
      { midi: 79, duration: 0.5, string: 0, fret: 15 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },
      { midi: 78, duration: 0.5, string: 0, fret: 14 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },

      { midi: 62, duration: 0.5, string: 3, fret: 12 },
      { midi: 74, duration: 0.5, string: 1, fret: 15 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },
      { midi: 67, duration: 0.5, string: 2, fret: 12 },
      { midi: 79, duration: 0.5, string: 0, fret: 15 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },
      { midi: 78, duration: 0.5, string: 0, fret: 14 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },

      { midi: 64, duration: 0.5, string: 3, fret: 14 },
      { midi: 74, duration: 0.5, string: 1, fret: 15 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },
      { midi: 67, duration: 0.5, string: 2, fret: 12 },
      { midi: 79, duration: 0.5, string: 0, fret: 15 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },
      { midi: 78, duration: 0.5, string: 0, fret: 14 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },

      { midi: 64, duration: 0.5, string: 3, fret: 14 },
      { midi: 74, duration: 0.5, string: 1, fret: 15 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },
      { midi: 67, duration: 0.5, string: 2, fret: 12 },
      { midi: 79, duration: 0.5, string: 0, fret: 15 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 },
      { midi: 78, duration: 0.5, string: 0, fret: 14 },
      { midi: 69, duration: 0.5, string: 2, fret: 14 }
    ]
  },
  {
    id: "enter_sandman",
    title: "Enter Sandman",
    artist: "Metallica",
    category: "Rock",
    bpm: 120,
    timeSignature: [4, 4],
    description: "Kult-Metal-Riff mit weiten Griffen (Bund 0 bis 7)",
    notes: [
      { midi: 40, duration: 1, string: 5, fret: 0 },
      { midi: 52, duration: 1, string: 4, fret: 7 },
      { midi: 55, duration: 1, string: 3, fret: 5 },
      { midi: 46, duration: 0.5, string: 5, fret: 6 },
      { midi: 45, duration: 0.5, string: 5, fret: 5 },
      { midi: 43, duration: 1, string: 5, fret: 3 },
      { midi: 40, duration: 3, string: 5, fret: 0 },

      { midi: 40, duration: 1, string: 5, fret: 0 },
      { midi: 52, duration: 1, string: 4, fret: 7 },
      { midi: 55, duration: 1, string: 3, fret: 5 },
      { midi: 46, duration: 0.5, string: 5, fret: 6 },
      { midi: 45, duration: 0.5, string: 5, fret: 5 },
      { midi: 43, duration: 1, string: 5, fret: 3 },
      { midi: 40, duration: 3, string: 5, fret: 0 },

      { midi: 40, duration: 1, string: 5, fret: 0 },
      { midi: 52, duration: 1, string: 4, fret: 7 },
      { midi: 55, duration: 1, string: 3, fret: 5 },
      { midi: 46, duration: 0.5, string: 5, fret: 6 },
      { midi: 45, duration: 0.5, string: 5, fret: 5 },
      { midi: 43, duration: 1, string: 5, fret: 3 },
      { midi: 40, duration: 3, string: 5, fret: 0 }
    ]
  },
  {
    id: "iron_man",
    title: "Iron Man",
    artist: "Black Sabbath",
    category: "Rock",
    bpm: 74,
    timeSignature: [4, 4],
    description: "Tony Iommis Heavy-Metal-Meilenstein entlang der A-Saite (Bund 2 bis 10)",
    notes: [
      { midi: 47, duration: 2, string: 4, fret: 2 },
      { midi: 50, duration: 1.5, string: 4, fret: 5 },
      { midi: 50, duration: 0.5, string: 4, fret: 5 },
      { midi: 52, duration: 2, string: 4, fret: 7 },
      { midi: 52, duration: 2, string: 4, fret: 7 },

      { midi: 55, duration: 0.5, string: 4, fret: 10 },
      { midi: 54, duration: 0.5, string: 4, fret: 9 },
      { midi: 55, duration: 0.5, string: 4, fret: 10 },
      { midi: 54, duration: 0.5, string: 4, fret: 9 },
      { midi: 55, duration: 1, string: 4, fret: 10 },
      { midi: 50, duration: 1, string: 4, fret: 5 },

      { midi: 50, duration: 1, string: 4, fret: 5 },
      { midi: 52, duration: 1.5, string: 4, fret: 7 },
      { midi: 52, duration: 1.5, string: 4, fret: 7 },

      { midi: 47, duration: 2, string: 4, fret: 2 },
      { midi: 50, duration: 1.5, string: 4, fret: 5 },
      { midi: 50, duration: 0.5, string: 4, fret: 5 },
      { midi: 52, duration: 2, string: 4, fret: 7 },
      { midi: 52, duration: 2, string: 4, fret: 7 }
    ]
  },
  {
    id: "sunshine",
    title: "Sunshine of Your Love",
    artist: "Cream (Eric Clapton)",
    category: "Rock",
    bpm: 115,
    timeSignature: [4, 4],
    description: "Eric Claptons berühmtes D-Blues-Riff (Bund 5 bis 12)",
    notes: [
      { midi: 62, duration: 1, string: 3, fret: 12 },
      { midi: 62, duration: 1, string: 3, fret: 12 },
      { midi: 60, duration: 1, string: 3, fret: 10 },
      { midi: 62, duration: 1, string: 3, fret: 12 },

      { midi: 56, duration: 1, string: 4, fret: 11 },
      { midi: 55, duration: 1, string: 4, fret: 10 },
      { midi: 53, duration: 1, string: 4, fret: 8 },
      { midi: 50, duration: 1, string: 4, fret: 5 },

      { midi: 62, duration: 1, string: 3, fret: 12 },
      { midi: 62, duration: 1, string: 3, fret: 12 },
      { midi: 60, duration: 1, string: 3, fret: 10 },
      { midi: 62, duration: 1, string: 3, fret: 12 },

      { midi: 56, duration: 1, string: 4, fret: 11 },
      { midi: 55, duration: 1, string: 4, fret: 10 },
      { midi: 53, duration: 1, string: 4, fret: 8 },
      { midi: 50, duration: 1, string: 4, fret: 5 }
    ]
  },
  {
    id: "back_in_black",
    title: "Back in Black",
    artist: "AC/DC (Angus Young)",
    category: "Rock",
    bpm: 92,
    timeSignature: [4, 4],
    description: "Kult-Akkorde, High-Lead-Lick (Bund 12-15) & chromatischer Turnaround",
    notes: [
      { midi: 40, duration: 1, string: 5, fret: 0 },
      { midi: 50, duration: 1, string: 3, fret: 0 },
      { midi: 45, duration: 2, string: 4, fret: 0 },

      { midi: 79, duration: 0.5, string: 0, fret: 15 },
      { midi: 76, duration: 0.5, string: 0, fret: 12 },
      { midi: 74, duration: 0.5, string: 1, fret: 15 },
      { midi: 71, duration: 0.5, string: 1, fret: 12 },
      { midi: 69, duration: 1, string: 2, fret: 14 },
      { midi: 40, duration: 1, string: 5, fret: 0 },

      { midi: 40, duration: 1, string: 5, fret: 0 },
      { midi: 50, duration: 1, string: 3, fret: 0 },
      { midi: 45, duration: 2, string: 4, fret: 0 },

      { midi: 47, duration: 0.5, string: 4, fret: 2 },
      { midi: 49, duration: 0.5, string: 4, fret: 4 },
      { midi: 47, duration: 0.5, string: 4, fret: 2 },
      { midi: 50, duration: 0.5, string: 4, fret: 5 },
      { midi: 47, duration: 0.5, string: 4, fret: 2 },
      { midi: 51, duration: 0.5, string: 4, fret: 6 },
      { midi: 47, duration: 0.5, string: 4, fret: 2 },
      { midi: 52, duration: 0.5, string: 4, fret: 7 }
    ]
  }
];

export function getBuiltinSong(id) {
  return BUILTIN_SONGS.find(s => s.id === id) || BUILTIN_SONGS[0];
}
