/**
 * Song-Katalog mit allen vorinstallierten Liedern.
 * Dient sowohl als statische Absicherung (z. B. bei Öffnen über file:// ohne Server)
 * als auch als Verzeichnis für dynamisches Nachladen.
 */

export const BUILTIN_SONGS = [
  {
    id: "smoke",
    title: "Smoke on the Water",
    artist: "Deep Purple",
    category: "Rock",
    bpm: 112,
    timeSignature: [4, 4],
    description: "Riff auf D- und G-Saite (Bund 0-3)",
    notes: [
      { midi: 50, duration: 1 },
      { midi: 53, duration: 1 },
      { midi: 55, duration: 2 },
      { midi: 50, duration: 1 },
      { midi: 53, duration: 1 },
      { midi: 56, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 50, duration: 1 },
      { midi: 53, duration: 1 },
      { midi: 55, duration: 2 },
      { midi: 53, duration: 1 },
      { midi: 50, duration: 1 },
      { midi: 50, duration: 2 }
    ]
  },
  {
    id: "seven_nation",
    title: "Seven Nation Army",
    artist: "The White Stripes",
    category: "Rock",
    bpm: 120,
    timeSignature: [4, 4],
    description: "Kult-Basslinie auf der Gitarre (E- und A-Saite)",
    notes: [
      { midi: 40, duration: 2 },
      { midi: 40, duration: 1 },
      { midi: 43, duration: 1 },
      { midi: 40, duration: 1 },
      { midi: 38, duration: 1 },
      { midi: 36, duration: 2 },
      { midi: 47, duration: 4 },
      { midi: 40, duration: 2 },
      { midi: 40, duration: 1 },
      { midi: 43, duration: 1 },
      { midi: 40, duration: 1 },
      { midi: 38, duration: 1 },
      { midi: 36, duration: 1 },
      { midi: 38, duration: 1 },
      { midi: 36, duration: 2 },
      { midi: 47, duration: 2 }
    ]
  },
  {
    id: "nem_intro",
    title: "Nothing Else Matters (Intro)",
    artist: "Metallica",
    category: "Rock",
    bpm: 92,
    timeSignature: [4, 4],
    description: "Berühmtes Fingerpicking-Intro auf leeren Saiten",
    notes: [
      { midi: 40, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 59, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 59, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 40, duration: 2 },
      { midi: 40, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 59, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 59, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 40, duration: 1 }
    ]
  },
  {
    id: "ode",
    title: "Ode an die Freude",
    artist: "Ludwig van Beethoven",
    category: "Klassik",
    bpm: 108,
    timeSignature: [4, 4],
    description: "Europahymne in C-Dur auf den hohen Saiten",
    notes: [
      { midi: 64, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 64, duration: 2 },
      { midi: 62, duration: 2 },
      { midi: 64, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 62, duration: 2 },
      { midi: 60, duration: 2 }
    ]
  },
  {
    id: "frere",
    title: "Frère Jacques",
    artist: "Traditional",
    category: "Traditionals",
    bpm: 100,
    timeSignature: [4, 4],
    description: "Klassischer Kanon (C-Dur)",
    notes: [
      { midi: 60, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 67, duration: 2 },
      { midi: 64, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 67, duration: 2 },
      { midi: 67, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 60, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 60, duration: 2 },
      { midi: 60, duration: 1 },
      { midi: 55, duration: 1 },
      { midi: 60, duration: 2 }
    ]
  },
  {
    id: "haenschen",
    title: "Hänschen klein",
    artist: "Traditional",
    category: "Traditionals",
    bpm: 104,
    timeSignature: [4, 4],
    description: "Traditionelles Volkslied (C-Dur)",
    notes: [
      { midi: 67, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 64, duration: 2 },
      { midi: 65, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 62, duration: 2 },
      { midi: 60, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 65, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 67, duration: 2 },
      { midi: 67, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 64, duration: 2 },
      { midi: 65, duration: 1 },
      { midi: 62, duration: 1 },
      { midi: 62, duration: 2 },
      { midi: 60, duration: 1 },
      { midi: 64, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 67, duration: 1 },
      { midi: 60, duration: 4 }
    ]
  }
];

export function getBuiltinSong(id) {
  return BUILTIN_SONGS.find(s => s.id === id) || BUILTIN_SONGS[0];
}
